### ISSUE TITLE
error

### ISSUE THREAD

**Issue by daixiaozhuan** [genomewalker/bam-filter#13]
Hi, 
when I run the filterBAM to filter the records with counts less than 5, it occurs an error:
"UnboundLocalError: local variable 'ref_lengths' referenced before assignment"

The command : filterBAM --min-read-count 5 R03MIRNAP221204850-1.mapped.sorted.bam

That'll be great if you can have a look at it.

**Comment by genomewalker** [comment]
Closing it. In case you still have the problem, re-open the issue.
