### ISSUE TITLE
Issue during BAM tempfile output - truncated file

### ISSUE THREAD

**Issue by Merritt-Brian** [genomewalker/bam-filter#39]
I'm using the `filter` and `reassign` commands after installing `v2.0` of `bam-filter` within a `conda env`. 

```
bam-filter          2.0.0
pysam               0.22.1
python               3.9.20
```

I, however, get this error during the sort step:

```
INFO ::: 2024-11-16 12:26:33 ::: ::: Using 1 cores to write 1 chunk(s)          
INFO ::: 2024-11-16 12:26:33 ::: ::: Collecting batches...                      
INFO ::: 2024-11-16 12:26:38 ::: Sorting BAM file by coordinates...             
Traceback (most recent call last):
  File "/Users/merribb1/Documents/Software/miniconda3/envs/bam-filter/bin/filterBAM", line 8, in <module>
    sys.exit(main())
  File "/Users/merribb1/Documents/Software/miniconda3/envs/bam-filter/lib/python3.9/site-packages/bam_filter/__main__.py", line 43, in main
    filter_references(args)
  File "/Users/merribb1/Documents/Software/miniconda3/envs/bam-filter/lib/python3.9/site-packages/bam_filter/filter.py", line 249, in filter_references
    filter_reference_BAM(
  File "/Users/merribb1/Documents/Software/miniconda3/envs/bam-filter/lib/python3.9/site-packages/bam_filter/sam_utils.py", line 1350, in filter_reference_BAM
    pysam.sort(
  File "/Users/merribb1/Documents/Software/miniconda3/envs/bam-filter/lib/python3.9/site-packages/pysam/utils.py", line 83, in __call__
    raise SamtoolsError(
pysam.utils.SamtoolsError: 'samtools returned with error 1: stdout=, stderr=samtools sort: truncated file. Aborting\n'
```

If i use `disable-sort` it creates the bam file but whenever I try to open it with `samtools view -h` I get the error:

`samtools view: error reading file "c55d4e2df1.dedup.filtered.bam": Result too large`

and If I run `samtools sort` on the file like so:

```
samtools sort  $workdir/c55d4e2df1.dedup.filtered.bam   > $workdir/c55d4e2df1.dedup.filtered.sorted.bam
```

I get the same error involving a `truncated file`

The bamFilter command I run is: 
```
filterBAM filter \
    --bam $workdir/aligned_sorted.bam \
    --bam-filtered $workdir/c55d4e2df1.dedup.filtered.bam \
    --stats $workdir/c55d4e2df1.dedup.stats.tsv.gz \
    --threads 1  \
    --include-low-detection \
    --disable-sort \
    --stats-filtered $workdir/c55d4e2df1.dedup.stats-filtered.tsv.gz 
```

I've tested this on OSX-arm64, OSX-amd64, and within an Ubuntu 20 system

**Comment by genomewalker** [comment]
Hi @Merritt-Brian 
Which Samtools version are you using?

**Comment by Merritt-Brian** [comment]
@genomewalker v1.21

**Comment by Merritt-Brian** [comment]
@genomewalker  This may be an issue with the way paired-end reads are processed. Testing with a `minimap2` sorted BAM file lets the process complete succesfully. However, it seems that with a paired-end set using either `minimap2` or `bowtie2` causes the error to take place (using the same FASTA as a reference upstream). 

An example alignment command with the r1 r2 set would be 

```
 minimap2 --MD -ax sr $workdir/all.fasta $r1 $r2 | samtools sort | samtools view -bh -q 10 -o $workdir/aligned_sorted.bam
```

However, if i just do: 

```
minimap2 --MD -ax sr $workdir/all.fasta $r1  \
    | samtools sort | samtools view -bh -q 0 -o $workdir/aligned_sorted.bam
```

The same (initial comment) command completes successfully

**Comment by genomewalker** [comment]
filter-bam only has been tested with bams from bowtie2 and is not designed to handle paired-end data. Eventually will add support for PE data.

**Comment by zhangwenda0518** [comment]
I recently discovered this tool, the same paired data failed, I would like to ask, what is the progress of adapting to dual-end data?🥺
